# Generated by Django 4.0.1 on 2022-01-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_alter_category_options_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('test', 'test')], default='uncategorized', max_length=50),
        ),
    ]
