# Generated by Django 4.0.1 on 2022-01-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('test', 'test'), ('new', 'new')], default='uncategorized', max_length=50),
        ),
    ]
