# Generated by Django 4.0.1 on 2022-02-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isWriter',
            field=models.BooleanField(default=False),
        ),
    ]
