# Generated by Django 4.0.1 on 2022-02-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_profile_isadmin_profile_iswriter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profpics/default-profile-pic.jpg', null=True, upload_to='profpics/'),
        ),
    ]
