# Generated by Django 4.0.1 on 2022-02-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0015_alter_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
