# Generated by Django 4.0.1 on 2022-02-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0017_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
