# Generated by Django 4.0.1 on 2022-02-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0018_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
